messages:
  # Valid Placeholders:
  #   - %blocked% - The player's origin/brand that was blocked
  #   - %blocktype% - Shows what the player was blocked for
  #   - %easyblocktype% - Shows what the player was blocked for in an eagler-kid readable form
  #   - %host% - The IP the player pinged
  #   - %help% - The configured help message for the block type

  kick: |
    <red>This %easyblocktype% is not allowed on the server!</red>
    <dark_gray>»</dark_gray> <gray>%blocked%</gray> <dark_gray>«</dark_gray>

    %help%
    
    <gray>Think this is a mistake? Join our discord:</gray>
    <blue>discord.gg/changethisintheconfig</blue>
  
  # Please note that help is only supported in the kick message, not the MOTD
  help:
    generic: "<gray>Please switch to a different %easyblocktype%.</gray>"
    player: "<gray>Please change your %easyblocktype%.</gray>"

  motd:
    enabled: true
    text: |
      <red>This %easyblocktype% is not allowed!</red>
      <dark_gray>»</dark_gray> <gray>%blocked%</gray> <dark_gray>«</dark_gray>
    icon: "blacklisted.png"

# Origin + Brand blacklist supports wildcards
# Everything should be lowercase
blacklist:
  origins:
    - "hack.example.com"
  brands:
    - "*dragonx*"
    - "*piclient*"
  players:
    - "Admin"

discord:
  webhook: ""

























# :>